#!/usr/bin/env python3
"""
generate_readme.py

Rebuilds the root README.md dashboard purely from the YAML frontmatter of
every solutions/*/*/README.md file. Never hand-edit the dashboard section —
it is fully derived and will be overwritten on the next sync.

Can also be run standalone any time:
    python scripts/generate_readme.py
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path
from datetime import datetime, timezone

import utils
from utils import iter_problem_readmes

MARKER_START = "<!-- DASHBOARD:START -->"
MARKER_END = "<!-- DASHBOARD:END -->"

GOAL_TOTAL = 300  # edit this to change your target; shown as a progress bar


def progress_bar(current: int, target: int, width: int = 24) -> str:
    if target <= 0:
        return ""
    filled = min(width, round(width * current / target))
    return "`[" + "#" * filled + "-" * (width - filled) + f"]` {current}/{target}"


def build_dashboard() -> str:
    problems = list(iter_problem_readmes())
    total = len(problems)

    difficulty_counts = Counter(p[1]["difficulty"] for p in problems)
    language_counts = Counter(p[1]["language"] for p in problems)
    topic_counts: Counter[str] = Counter()
    for _, meta, _ in problems:
        for tag in meta.get("pattern", []) or []:
            topic_counts[tag] += 1

    recent = sorted(problems, key=lambda p: p[1]["date_solved"], reverse=True)[:10]
    stale = sorted(
        (p for p in problems if p[1]["difficulty"] in ("Medium", "Hard")),
        key=lambda p: p[1]["date_solved"],
    )[:10]

    lines: list[str] = []
    lines.append(MARKER_START)
    lines.append("")
    lines.append("## 📊 LeetCode Progress")
    lines.append("")
    lines.append(f"**Total solved: {total}**")
    lines.append("")
    lines.append(progress_bar(total, GOAL_TOTAL))
    lines.append("")
    lines.append("| Difficulty | Count |")
    lines.append("|---|---|")
    for diff in ("Easy", "Medium", "Hard"):
        lines.append(f"| {diff} | {difficulty_counts.get(diff, 0)} |")
    lines.append("")

    if topic_counts:
        lines.append("### Topics")
        lines.append("")
        lines.append("| Topic | Solved |")
        lines.append("|---|---|")
        for topic, count in topic_counts.most_common():
            lines.append(f"| {topic} | {count} |")
        lines.append("")

    if language_counts:
        lines.append("### Languages")
        lines.append("")
        lines.append("| Language | Solved |")
        lines.append("|---|---|")
        for lang, count in language_counts.most_common():
            lines.append(f"| {lang} | {count} |")
        lines.append("")

    if recent:
        lines.append("### Recently Solved")
        lines.append("")
        for path, meta, _ in recent:
            rel = path.relative_to(utils.SOLUTIONS_DIR.parent).as_posix()
            link = "/".join(rel.split("/")[:-1])  # dir, README.md linked implicitly
            lines.append(
                f"- [{meta['leetcode_id']}. {meta['title']}]({link}) "
                f"— {meta['difficulty']} — {meta['date_solved']}"
            )
        lines.append("")

    if topic_counts:
        least_practiced = topic_counts.most_common()[:-6:-1]
        if least_practiced:
            lines.append("### Least-Practiced Patterns")
            lines.append("")
            for topic, count in least_practiced:
                lines.append(f"- {topic} ({count})")
            lines.append("")

    if stale:
        lines.append("### Candidates for Revision (oldest Medium/Hard)")
        lines.append("")
        for path, meta, _ in stale:
            rel = path.relative_to(utils.SOLUTIONS_DIR.parent).as_posix()
            link = "/".join(rel.split("/")[:-1])
            lines.append(
                f"- [{meta['leetcode_id']}. {meta['title']}]({link}) "
                f"— {meta['difficulty']} — solved {meta['date_solved']}"
            )
        lines.append("")

    lines.append(f"_Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_")
    lines.append("")
    lines.append(MARKER_END)
    return "\n".join(lines)


STATIC_HEADER = """# LeetCode → GitHub Tracker

This repository is automatically synced from my LeetCode Accepted
submissions. See [`scripts/sync.py`](scripts/sync.py) for how it works, and
[`scripts/revision.py`](scripts/revision.py) for revision commands like:

```bash
python scripts/revision.py --topic binary-search
python scripts/revision.py --difficulty medium
python scripts/revision.py --old
python scripts/revision.py --random
```

Everything between the dashboard markers below is generated by
`scripts/generate_readme.py` — do not edit it by hand, it will be
overwritten on the next sync.

"""


def main() -> int:
    readme_path = utils.SOLUTIONS_DIR.parent / "README.md"
    dashboard = build_dashboard()

    if readme_path.exists():
        existing = readme_path.read_text(encoding="utf-8")
        if MARKER_START in existing and MARKER_END in existing:
            before = existing.split(MARKER_START)[0]
            after = existing.split(MARKER_END)[1]
            new_content = before + dashboard + after
        else:
            new_content = STATIC_HEADER + dashboard + "\n"
    else:
        new_content = STATIC_HEADER + dashboard + "\n"

    readme_path.write_text(new_content, encoding="utf-8")
    print(f"Wrote {readme_path}")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
